#ifndef TOOLIB_HPP_N3G8XW9SQJ3SSK3UTM3Q
#define TOOLIB_HPP_N3G8XW9SQJ3SSK3UTM3Q

#include "mb/toolib/config.hpp"
#include "mb/toolib/console/prompt.hpp"
#include "mb/toolib/date_time/cal_event.hpp"
#include "mb/toolib/date_time/date_time.hpp"
#include "mb/toolib/filesys/file_collection.hpp"
#include "mb/toolib/filesys/path.hpp"
#include "mb/toolib/financial/money.hpp"
#include "mb/toolib/game/game.hpp"
#include "mb/toolib/image/color.hpp"
#include "mb/toolib/image/image.hpp"
#include "mb/toolib/math/geometry.hpp"
#include "mb/toolib/math/graph.hpp"
#include "mb/toolib/math/matrix.hpp"
#include "mb/toolib/math/minmax_values.hpp"
#include "mb/toolib/math/pair.hpp"
#include "mb/toolib/math/percent.hpp"
#include "mb/toolib/math/quantity_unit.hpp"
#include "mb/toolib/math/scale.hpp"
#include "mb/toolib/math/stat/histogram.hpp"
#include "mb/toolib/scope/raii_p.hpp"
#include "mb/toolib/scope/reftovalue.hpp"
#include "mb/toolib/scope/scopeguard.hpp"
#include "mb/toolib/type/counted_class_objects.hpp"
#include "mb/toolib/type/iabstract.hpp"
#include "mb/toolib/type/itype.hpp"

#endif
