<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <CUSTOM_POSTBUILDCOPY_BIN_PATH>$(SolutionDir)bin/$(Configuration)/</CUSTOM_POSTBUILDCOPY_BIN_PATH>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup>
    <PostBuildEvent>
      <Command>if not exist "$(CUSTOM_POSTBUILDCOPY_BIN_PATH)" mkdir "$(CUSTOM_POSTBUILDCOPY_BIN_PATH)"
copy "$(TargetPath)" "$(CUSTOM_POSTBUILDCOPY_BIN_PATH)"
</Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="CUSTOM_POSTBUILDCOPY_BIN_PATH">
      <Value>$(CUSTOM_POSTBUILDCOPY_BIN_PATH)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
  </ItemGroup>
</Project>