name: build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        preset: [debug, relwithdebinfo]
        config:
          - {os: ubuntu-24.04,  compiler: GNU,  CC: gcc-14,   CXX: g++-14,     warnall: ON,  clanglib: OFF}
          #todo clanglib ON as soon as packages below are installable again
          - {os: ubuntu-24.04,  compiler: LLVM, CC: clang-18, CXX: clang++-18, warnall: ON,  clanglib: OFF}

    env:
      CC: ${{matrix.config.CC}}
      CXX: ${{matrix.config.CXX}}

    # The CMake configure and build commands are platform-agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{matrix.config.os}}

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: recursive

#todo also see comment above
# currently not found :(
#     - name: Install libc++
#       if: ${{startsWith(matrix.config.os, 'ubuntu')}}
#       run: >
#         sudo apt-get install -y libc++abi-18-dev libc++-18-dev

    - name: Configure CMake
      run: >
        cmake --preset ${{matrix.preset}}
        -DUL_ALL_WARNINGS=${{matrix.config.warnall}}
        -DUL_USE_CLANG_STDLIB=${{matrix.config.clanglib}}

    - name: Build
      run: cmake --build --preset ${{matrix.preset}}

    - name: Test
      run: ctest --preset ${{matrix.preset}}
